name: Cypress CI/CD
on: 
  schedule:
    - cron: '*/5 * * * *'
  push: 
    branches: [main, master]
  pull_request: 
    branches: [main, master]
jobs: 
  cypress-run:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
         browser: [chrome, edge] 
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cypress.io
        uses: cypress-io/github-action@v6.5.0
        with:
          browser: ${{ matrix.browser }}