name: Cypress CI/CD
on: 
  schedule:
    - cron: '*/5 * * * *'
  push: 
    branches: [main, master]
  pull_request: 
    branches: [main, master]
jobs: 
  smoke-run:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        browser: [chrome, edge] 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn tsc --noEmit

      - name: Run smoke tests on Cypress.io
        uses: cypress-io/github-action@v6.5.0
        with:
          browser: ${{ matrix.browser }}
          script: npm run cypress:smoke
  
  tagtest-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, edge]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: npm install

      - name: Debug
        run: |
            echo "Tags: $TAGS"
            npm run cy:run -- --spec "cypress/integration/**/*.feature" --env TAGS="$TAGS"
        env:
          TAGS: "@Tagtest" 

      - name: Run tag tests on Cypress.io
        uses: cypress-io/github-action@v6.5.0
        with:
          browser: ${{ matrix.browser }}
          script: npm run cypress:tagtest
